version: 1.0.{build}

install:
  - SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
configuration: Release
platform:
- x64
- Win32
nuget:
  disable_publish_on_pr: true
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  project: JavaLauncher.sln
  verbosity: minimal
artifacts:
- path: build\Win32\Release\JavaLauncher-Win32.exe
  name: Win32
- path: build\x64\Release\JavaLauncher-x64.exe
  name: x64
