version: 1.0.{build}

environment:
  VisualStudioVersion: 14.0
configuration: Release
platform:
- x64
- Win32
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: nuget.exe restore
build:
  project: JavaLauncher.vcxproj
  verbosity: minimal
artifacts:
- path: build\Win32\Release\JavaLauncher-Win32.exe
  name: Win32
- path: build\x64\Release\JavaLauncher-x64.exe
  name: x64
cache:
- packages -> **\packages.config
